#!/usr/bin/env python

"""

CleanAll


A script that cleans up all the stuff used for TAP batch mode


"""

raise NotImplementedError("This hasn't been written yet -- but it's a good idea!")

import os

def CleanAll(copy=True):
    """
    removes everything generated by the TAP scripts
     
    if copy==True (default) it will copy it to backup names.
    """
    if copy:
        # create a back-up dir
        pass
    # remove StartTimes
    
